name: Notify deployment

inputs:
  title:
    description: 'Job title'
    required: true
  webhookUrl:
    description: 'Discord Webhook URL for sending the notifications.'
    required: true
  resultUrl:
    description: 'URL for the deployment'
    required: true
  status:
    description: 'Status of the deployment (success/failure)'
    required: true
  notify_when:
    description: 'When to send notification (always/failure_only)'
    required: false
    default: 'always'

runs:
  using: 'composite'
  steps:
    - name: Notify deployment status
      if: inputs.notify_when == 'always' && (inputs.status == 'success' || inputs.status == 'failure') || (inputs.notify_when == 'failure_only' && inputs.status == 'failure')
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: ${{ inputs.status == 'success' && 'info' || 'error' }}
        details: >-
          ${{ 
            inputs.status == 'success' 
              && format('Deployment SUCCESS for {0}. Visit {1}', inputs.title, inputs.resultUrl)
              || format('Deployment FAILURE for {0}', inputs.title)
          }}
        webhookUrl: ${{ inputs.webhookUrl }}
