export const ERROR_LOG_MESSAGE = {
  FAILED_TO_FETCH_IMAGE: 'FAILED_TO_FETCH_IMAGE',
  GET_OPTIMIZED_IMAGE_ERROR: 'GET_OPTIMIZED_IMAGE_ERROR',
  MISSING_IMAGE_URL: 'MISSING_IMAGE_URL',
} as const;

export const INFO_LOG_MESSAGE = {
  OPTIMIZE_IMAGE_SUCCESS: 'OPTIMIZE_IMAGE_SUCCESS',
} as const;
