export const ERROR_LOG_MESSAGE = {
  GENERAL_SERVER_ERROR: 'GENERAL_SERVER_ERROR',
  STREAMING_RENDERING_ERROR: 'STREAMING_RENDERING_ERROR',
} as const;

export const WARNING_LOG_MESSAGE = {
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
};

export const INFO_LOG_MESSAGE = {
  INCOMING_REQUEST: 'INCOMING_REQUEST',
} as const;
