name: 'CI: Validate PR Title'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify job status
        if: always()
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate PR Title'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          notify_when: failure_only
