name: 'CI: Validate PR'

on: pull_request

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-dependencies
      - name: Notify job status
        if: always()
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate PR -> Install dependencies'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          notify_when: failure_only

  lint:
    name: Lint
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-dependencies
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          safe_output: false
      - name: Lint
        id: lint
        if: steps.changed-files.outputs.all_changed_files
        env:
          FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          FILTERED_FILES="$(echo $FILES | tr " " "\n" | grep -E "(.*)\.(ts|tsx)$" || true)"
          bun run lint $FILTERED_FILES
      - name: Notify job status
        if: always()
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate PR -> Lint'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          notify_when: failure_only

  test:
    name: Test
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-dependencies
      - name: Test
        run: bun run test:coverage
      - name: Notify job status
        if: always()
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate PR -> Test'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          notify_when: failure_only
