name: 'CI: Validate Main Branch'

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-dependencies
      - name: Notify job status
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate Main Branch -> Install dependencies'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}

  lint:
    name: Lint
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-dependencies
      - name: Lint
        run: bun run lint .
      - name: Notify job status
        uses: './.github/actions/notify-job-status'
        with:
          title: 'CI: Validate Main Branch -> Lint'
          webhookUrl: ${{ env.DISCORD_WEBHOOK_URL }}
